In [0]:
def ff(name, last, age=None):
    dd = {'name':name, 'last':last}
    if age:
        dd['age'] = age
    return dd

In [2]:
ff('ali', 'borji')

{'last': 'borji', 'name': 'ali'}

In [3]:
ff('ali', 'borji', 40)

{'age': 40, 'last': 'borji', 'name': 'ali'}

In [4]:
dic = {'age': 40, 'last': 'borji', 'name': 'ali'}
for i, j in dic.items():
    print(i, j)

age 40
last borji
name ali


In [5]:
ss= "age 40 last borji name ali"
ww= ss.split(" ")
ww

['age', '40', 'last', 'borji', 'name', 'ali']

In [6]:
"+".join(ww)

'age+40+last+borji+name+ali'

In [0]:
def print_models(unprinted, printed):
  while unprinted:
    m = unprinted.pop(0)
    print(m + ' ' + 'is done!')
    printed.append(m)
   

In [0]:
orig = ['a', 'b', 'c']
new = []

In [14]:
print_models(orig.copy(), new)
# print_models(orig, new)
print(orig)
print(new)

a is done!
b is done!
c is done!
['a', 'b', 'c']
['a', 'b', 'c']


In [20]:
a= 10
print(F"{10.1} is good {a}")

10.1 is good 10


In [0]:
def make_user(first, last, **more):
    info = {'name':first, 'last':last}
    for key, val in more.items():
      info[key] = val
    return info

# def make_user2(first, last, *more):
#     info = {'name':first, 'last':last}
#     for t in more:
#       info[key] = val
#     return info    

In [22]:
print(make_user('ali', 'bor'))


{'name': 'ali', 'last': 'bor'}


In [29]:
print(make_user('ali', 'bor', ield = 'dd', ss = 'jj'))

{'name': 'ali', 'last': 'bor', 'ield': 'dd', 'ss': 'jj'}


In [30]:
print(make_user('ali', 'bor', xx = {'ield':'dd', 'ss':'jj'}))

{'name': 'ali', 'last': 'bor', 'xx': {'ield': 'dd', 'ss': 'jj'}}


In [179]:
ll = [10,2,2,4,5,6]
ll.append(7)
print(ll)

[10, 2, 2, 4, 5, 6, 7]


In [180]:
ll.count(2)

2

In [181]:
sorted(ll)

[2, 2, 4, 5, 6, 7, 10]

In [37]:
ll.pop(-1)

7

In [0]:
# in place sorting
ll.sort(reverse=True)


In [182]:
ll

[10, 2, 2, 4, 5, 6, 7]

In [0]:
ll[::-1]

[2, 2, 4, 5, 6, 7, 10]

In [0]:
ll.extend([40,10,100])

In [55]:
ll

[10, 2, 2, 4, 5, 6, 7, 40, 10, 100]

In [0]:
del ll[1]

In [57]:
ll

[10, 2, 4, 5, 6, 7, 40, 10, 100]

In [0]:
ll.reverse()

In [59]:
ll

[100, 10, 40, 7, 6, 5, 4, 2, 10]

In [60]:
ll.index(10)

1

In [0]:
ll.remove(100)

In [62]:
ll

[10, 40, 7, 6, 5, 4, 2, 10]

In [63]:
set(ll)

{2, 4, 5, 6, 7, 10, 40}

In [0]:
t = ll.pop()

In [67]:
ll

[10, 40, 7, 6, 5, 4]

In [0]:
t

10

In [0]:
u =sorted(ll)

In [69]:
u

[4, 5, 6, 7, 10, 40]

In [0]:
ll.sort()

In [0]:
ll

[2, 2, 4, 5, 6, 10, 40]

In [0]:
list(range(1,20,2))[::2]

[1, 5, 9, 13, 17]

In [0]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [0]:
sum(ll)

69

In [0]:
max(ll)

40

In [0]:
sum([i**2 for i in ll])

1785

In [0]:
dd = {'a':10}

In [83]:
for i in ['a', 'b']:
  w= dd.get(i,'non xistaned')
  print(w)


10
non xistaned


In [79]:
print(w)

10


In [0]:
# keys are sorted!!!
from collections import OrderedDict

In [0]:
oo = OrderedDict()

In [0]:
oo['t'] = 10
oo['a'] = 0
oo['z'] = 100



In [89]:
oo

OrderedDict([('a', 0), ('z', 100), ('t', 10)])

In [93]:
for i,j in oo.items():
  print(i +  ' : ' + str(j))

t : 10
a : 0
z : 100


In [94]:
ls

sample_data/


In [0]:
mkdir tt

In [96]:
ls

sample_data/  tt/


In [0]:
with open('test.txt', 'w') as f:
  for t in range(5):
    f.write(str(t) + '\n')

In [98]:
ls

sample_data/  test.txt  tt/


In [104]:
# !less test.txt
cat test.txt

0
1
2
3
4


In [107]:
with open('test.txt', 'r') as f:
  for line in f:
    # print(line)
    print(line.rstrip())

0
1
2
3
4


In [108]:
with open('test.txt', 'r') as f:
    print(f.readlines())

['0\n', '1\n', '2\n', '3\n', '4\n']


In [0]:
import numpy as np


In [110]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [166]:
a  =np.random.random((3,3))
print(a)

[[0.13638458 0.0278735  0.35580704]
 [0.21234509 0.5577228  0.49294955]
 [0.14663724 0.1143837  0.73346863]]


In [115]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [162]:
np.empty((3,3))

array([[0.2647706 , 0.17195851, 0.06987201],
       [0.55394499, 0.5118955 , 0.32389361],
       [0.93830023, 0.71947796, 0.83342978]])

In [118]:
a.shape

(3, 3)

In [122]:
a.ndim

2

In [0]:
# a.numel()

In [126]:
np.size(a)

9

In [127]:
len(a)

3

In [130]:
a.dtype

dtype('float64')

In [131]:
type(a)

numpy.ndarray

In [134]:
a.size

9

In [135]:
a.tolist()

[[0.2647706029520164, 0.1719585143011163, 0.06987200524699222],
 [0.5539449866635895, 0.5118954986530054, 0.32389360780299004],
 [0.9383002307198233, 0.7194779636545359, 0.8334297831369224]]

In [141]:
print(np.info(len))

None


In [0]:
np.array([1,2,3]) * np.array([4,5,6])

array([ 4, 10, 18])

In [142]:
np.array([1,2,3]).dot(np.array([4,5,6]))

32

In [0]:
a.shape
a = a.reshape(-1,9)

In [165]:
a.shape

(1, 9)

In [0]:
a.sort(axis=1)

In [164]:
a
# help(a.view)

array([[0.06987201, 0.17195851, 0.2647706 , 0.32389361, 0.5118955 ,
        0.55394499, 0.71947796, 0.83342978, 0.93830023]])

In [0]:
a.T

array([[0.1955378 , 0.5452641 , 0.65568935],
       [0.23110752, 0.55687009, 0.86269038],
       [0.27229903, 0.70755142, 0.96119854]])

In [0]:
a.transpose()

array([[0.1955378 , 0.5452641 , 0.65568935],
       [0.23110752, 0.55687009, 0.86269038],
       [0.27229903, 0.70755142, 0.96119854]])

In [0]:
import operator

In [0]:
s1 = "geeksfor"
s2 = "geeks"

In [173]:
print (operator.concat(s1,s2)) 

geeksforgeeks


In [175]:
' '.join([s1,s2])

'geeksfor geeks'

In [176]:
if (operator.contains(s1,s2)): 
  print("geeksfor contains geeks") 
else: 
  print("geeksfor does not contain geeks") 


geeksfor contains geeks


In [177]:
ss = 'aliborji'
ss[0]
ss[~0]

'i'

In [0]:
ss[-1]

'i'

In [186]:
# sorting a dictionary
prices = {'Apple': 1.99, 'Banana': 0.99, 'Orange': 1.49, 'Cantaloupe': 3.99, 'Grapes': 0.39}
print(sorted(prices.items(), key = lambda x : x[1]))

[('Grapes', 0.39), ('Banana', 0.99), ('Orange', 1.49), ('Apple', 1.99), ('Cantaloupe', 3.99)]


In [187]:
prices

{'Apple': 1.99,
 'Banana': 0.99,
 'Cantaloupe': 3.99,
 'Grapes': 0.39,
 'Orange': 1.49}

In [0]:
prices = OrderedDict(sorted(prices.items(), key = lambda x : x[1]))

In [194]:
dict(prices)

{'Apple': 1.99,
 'Banana': 0.99,
 'Cantaloupe': 3.99,
 'Grapes': 0.39,
 'Orange': 1.49}

In [195]:

# Initializing list of dictionaries 
lis = [{ "name" : "Nandini", "age" : 20},  { "name" : "Manjeet", "age" : 20 },  { "name" : "Nikhil" , "age" : 19 }] 

# using sorted and lambda to print list sorted by age 
# print "The list printed sorting by age: "
print(sorted(lis, key = lambda x: x['age']) )

print ("\r") 

[{'name': 'Nikhil', 'age': 19}, {'name': 'Nandini', 'age': 20}, {'name': 'Manjeet', 'age': 20}]



In [205]:
# most frequent item()
test = [1, 2, 3, 4, 2, 2, 3, 1, 4, 4, 4,2,2,2,4,4,4] 
print(max(test, key = test.count)) 


4


In [201]:
set(test)
print(test.count)

<built-in method count of list object at 0x7f04fbeaa7c8>


In [0]:
(test.count)

<function list.count>

In [0]:
print(max((test), key = test.count)) 


2


In [0]:
set(test)

{1, 2, 3, 4}

In [206]:
from collections import Counter 

Counter('geek')

Counter({'e': 2, 'g': 1, 'k': 1})

In [210]:
list(enumerate('abc',5)) 


[(5, 'a'), (6, 'b'), (7, 'c')]

In [212]:
def fib(num):
    a,b = 0,1
    for i in range(0, num):
        # print "{}: {}".format(i+1, a)  # This will cause a problem in the following loop
        # yield "{}: {}".format(i+1, a)  # This will cause a problem in the following loop
        yield f"{i+1}: {a}"  # This will cause a problem in the following loop
        a, b = b, a + b

for item in fib(10):
    print(item)


1: 0
2: 1
3: 1
4: 2
5: 3
6: 5
7: 8
8: 13
9: 21
10: 34


In [214]:
sorted("check")
''.join(sorted("check"))

'ccehk'

In [238]:
class Compute:
    def __init__(self):
        self.last = 3
        # return self.last


    def __iter__(self):
        self.last = 10
        return self.last

    def next(self):
        rv = self.last
        self.last += 1
        if self.last > 100:
            raise StopIteration()

        # sleep(.5)
        return rv

# print(compute())

ss = Compute()
for val in range(10):
    print(ss.next())
# ss.next()
# ss.next()


3
4
5
6
7
8
9
10
11
12


In [217]:
ss

In [245]:
import time
def compute():
    for i in range(10):
        time.sleep(.5)
        yield i

for val in compute():
    print(val)


0
1
2
3
4
5
6
7
8
9


In [0]:
 de = 'decs'
 de.split()

['decs']