In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[5.4246e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4887, 0.1966, 0.9892],
        [0.6966, 0.0814, 0.0869],
        [0.2007, 0.1381, 0.8954],
        [0.5883, 0.8947, 0.5416],
        [0.3836, 0.7626, 0.2936]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [10]:
x = torch.tensor([5.5, 3])
print(x)
type(x)
x.dtype

tensor([5.5000, 3.0000])


torch.float32

or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7182, -1.0426, -1.0071],
        [ 1.5678,  0.4671,  0.2586],
        [-1.1833, -0.9866, -0.0068],
        [ 0.4558, -0.8096, -2.0168],
        [-2.2882, -1.6204,  0.6450]])


Get its size:



In [12]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3433, -0.6305, -0.8122],
        [ 1.7557,  0.6613,  0.4884],
        [-0.7020, -0.2528,  0.7768],
        [ 1.2921, -0.6282, -1.3532],
        [-1.5783, -0.6601,  1.4423]])


Addition: syntax 2



In [14]:
print(torch.add(x, y))

tensor([[ 1.3433, -0.6305, -0.8122],
        [ 1.7557,  0.6613,  0.4884],
        [-0.7020, -0.2528,  0.7768],
        [ 1.2921, -0.6282, -1.3532],
        [-1.5783, -0.6601,  1.4423]])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3433, -0.6305, -0.8122],
        [ 1.7557,  0.6613,  0.4884],
        [-0.7020, -0.2528,  0.7768],
        [ 1.2921, -0.6282, -1.3532],
        [-1.5783, -0.6601,  1.4423]])


Addition: in-place



In [18]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.7798, -2.7157, -2.8264],
        [ 4.8912,  1.5956,  1.0055],
        [-3.0685, -2.2260,  0.7632],
        [ 2.2037, -2.2474, -5.3867],
        [-6.1547, -3.9008,  2.7322]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [19]:
print(x[:, 1])

tensor([-1.0426,  0.4671, -0.9866, -0.8096, -1.6204])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
y

tensor([ 0.0690, -1.5448, -0.3981, -1.0570, -1.0793,  0.7269, -0.0744, -1.9354,
        -1.2917, -0.1198, -0.7047, -0.1045,  0.4690,  1.4988, -0.1929, -1.5115])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9081])
-0.9080893993377686


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [30]:
torch.cuda.is_available()

False